#!/bin/sh

# 1. 无登录密码
passwd -d root
uci set system.@system[0].password=''
uci commit system

# 2. 局域网 IP 已是 192.168.1.1（默认）

# 3. 开启 WiFi + 设置 SSID
uci set wireless.radio0.disabled='0'
uci set wireless.default_radio0.ssid='Cudy'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='password'   # 请自行修改，或留空

uci set wireless.radio1.disabled='0'
uci set wireless.default_radio1.ssid='Cudy-5G'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='password'

uci commit wireless
wifi reload

# 4. USB 网络接口（RNDIS 常见为 usb0）
uci set network.usbwan=interface
uci set network.usbwan.proto='dhcp'
uci set network.usbwan.device='usb0'
uci set network.usbwan.metric='20'
uci commit network

# 5. mwan3 双 WAN 自动切换（WAN 优先，USB 备用）
uci set mwan3.wan=interface
uci set mwan3.wan.enabled='1'
uci set mwan3.wan.family='ipv4'
uci set mwan3.wan.track_method='ping'
uci set mwan3.wan.reliability='1'
uci set mwan3.wan.count='1'
uci set mwan3.wan.timeout='2'
uci set mwan3.wan.interval='5'
uci set mwan3.wan.down='3'
uci set mwan3.wan.up='3'

uci set mwan3.usbwan=interface
uci set mwan3.usbwan.enabled='1'
uci set mwan3.usbwan.family='ipv4'
uci set mwan3.usbwan.track_method='ping'
uci set mwan3.usbwan.reliability='1'
uci set mwan3.usbwan.count='1'
uci set mwan3.usbwan.timeout='2'
uci set mwan3.usbwan.interval='5'
uci set mwan3.usbwan.down='3'
uci set mwan3.usbwan.up='3'

# 成员与策略
uci set mwan3.wan_m1_w3=member
uci set mwan3.wan_m1_w3.interface='wan'
uci set mwan3.wan_m1_w3.metric='1'
uci set mwan3.wan_m1_w3.weight='3'

uci set mwan3.usbwan_m2_w2=member
uci set mwan3.usbwan_m2_w2.interface='usbwan'
uci set mwan3.usbwan_m2_w2.metric='2'
uci set mwan3.usbwan_m2_w2.weight='2'

uci set mwan3.wan_only=policy
uci set mwan3.wan_only.last_resort='unreachable'
uci add_list mwan3.wan_only.use_member='wan_m1_w3'

uci set mwan3.balanced=policy
uci set mwan3.balanced.last_resort='unreachable'
uci add_list mwan3.balanced.use_member='wan_m1_w3'
uci add_list mwan3.balanced.use_member='usbwan_m2_w2'

uci set mwan3.default_rule_v4=rule
uci set mwan3.default_rule_v4.dest_ip='0.0.0.0/0'
uci set mwan3.default_rule_v4.family='ipv4'
uci set mwan3.default_rule_v4.use_policy='balanced'

uci commit mwan3
/etc/init.d/mwan3 enable
/etc/init.d/mwan3 restart

# 6. UPnP 默认开启
uci set upnpd.config.enabled='1'
uci commit upnpd
/etc/init.d/miniupnpd enable
/etc/init.d/miniupnpd start

exit 0
